-- ==============================================================================
-- Singapore Weather AI - Physical Data Model (Snowflake DDL)
-- Target Platform: Snowflake
-- Source: Existing local SQLite database (services/api/weather.db)
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. Create Schema
-- ------------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS WEATHER_AI_DB.API_CACHE;

USE SCHEMA WEATHER_AI_DB.API_CACHE;

-- ------------------------------------------------------------------------------
-- 2. Core Entities (Dimensions / Base Tables)
-- ------------------------------------------------------------------------------

-- 2.1 User Activity (Query logs)
CREATE TABLE IF NOT EXISTS USER_ACTIVITY (
    QUERY_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOT NULL,
    QUERY TEXT NOT NULL,
    RESPONSE_TIME_MS FLOAT,
    FORECAST_OUTCOME VARCHAR(255),
    IP_ADDRESS VARCHAR(45),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_USER_ACTIVITY PRIMARY KEY (QUERY_ID)
);

-- 2.2 Place (Geographic areas/landmarks)
CREATE TABLE IF NOT EXISTS PLACE (
    PLACE_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOT NULL,
    PLACE_NAME VARCHAR(255) NOT NULL,
    PLACE_TYPE VARCHAR(50) DEFAULT 'point',
    CENTER_LAT FLOAT,
    CENTER_LON FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PLACE PRIMARY KEY (PLACE_ID),
    CONSTRAINT UK_PLACE_NAME UNIQUE (PLACE_NAME)
);

-- 2.3 Location (Specific lat/lon points linked to a place)
CREATE TABLE IF NOT EXISTS LOCATION (
    LOC_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOT NULL,
    PLACE_ID NUMBER(38,0) NOT NULL,
    LAT FLOAT NOT NULL,
    LON FLOAT NOT NULL,
    POINT_INDEX NUMBER(38,0),
    LABEL VARCHAR(255),
    CONSTRAINT PK_LOCATION PRIMARY KEY (LOC_ID),
    CONSTRAINT FK_LOC_PLACE FOREIGN KEY (PLACE_ID) REFERENCES PLACE(PLACE_ID)
);

-- 2.4 User Intent Activity (Cycling, Walking, etc. linked to a query)
CREATE TABLE IF NOT EXISTS ACTIVITY (
    ACTIVITY_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOT NULL,
    QUERY_ID NUMBER(38,0) NOT NULL,
    ACTIVITY_NAME VARCHAR(100) NOT NULL,
    RAIN_TOLERANCE FLOAT,
    CONSTRAINT PK_ACTIVITY PRIMARY KEY (ACTIVITY_ID),
    CONSTRAINT FK_ACT_QUERY FOREIGN KEY (QUERY_ID) REFERENCES USER_ACTIVITY(QUERY_ID)
);

-- ------------------------------------------------------------------------------
-- 3. Results (Fact Tables)
-- ------------------------------------------------------------------------------

-- 3.1 Forecast Results
CREATE TABLE IF NOT EXISTS FORECAST_RESULT (
    FORECAST_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOT NULL,
    QUERY_ID NUMBER(38,0),
    LOC_ID NUMBER(38,0),
    RAINFALL_MM FLOAT,
    STATUS VARCHAR(100),
    CONFIDENCE FLOAT,
    IS_RISKY NUMBER(1,0) DEFAULT 0, -- SQLite INTEGER used as Boolean
    RESPONSE_TIME_MS FLOAT,
    FORECAST_TIME TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FORECAST_RESULT PRIMARY KEY (FORECAST_ID),
    CONSTRAINT FK_FCST_QUERY FOREIGN KEY (QUERY_ID) REFERENCES USER_ACTIVITY(QUERY_ID),
    CONSTRAINT FK_FCST_LOC FOREIGN KEY (LOC_ID) REFERENCES LOCATION(LOC_ID)
);

-- 3.2 Actual Observations
CREATE TABLE IF NOT EXISTS ACTUAL_RESULT (
    ACTUAL_ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOT NULL,
    LOC_ID NUMBER(38,0) NOT NULL,
    ACTUAL_RAINFALL_MM FLOAT,
    SOURCE VARCHAR(50) DEFAULT 'NEA',
    OBSERVATION_TIME TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ACTUAL_RESULT PRIMARY KEY (ACTUAL_ID),
    CONSTRAINT FK_ACTUAL_LOC FOREIGN KEY (LOC_ID) REFERENCES LOCATION(LOC_ID)
);

-- 3.3 Legacy Search History (Retained for completeness)
CREATE TABLE IF NOT EXISTS SEARCH_HISTORY (
    ID NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOT NULL,
    QUERY TEXT NOT NULL,
    IP_ADDRESS VARCHAR(45),
    RESPONSE_TIME_MS FLOAT,
    RESPONSE_RESULT TEXT,
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SEARCH_HISTORY PRIMARY KEY (ID)
);
